2024-02-04 14:09:12,260:DEBUG:certbot._internal.main:certbot version: 2.8.0
2024-02-04 14:09:12,261:DEBUG:certbot._internal.main:Location of certbot entry point: /usr/local/bin/certbot
2024-02-04 14:09:12,261:DEBUG:certbot._internal.main:Arguments: ['--webroot', '--webroot-path=/usr/share/nginx/html/letsencrypt', '--email', 'desarrollo.jadalsoftware@gmail.com', '--agree-tos', '--no-eff-email', '-d', 'migracion.jadal.pe']
2024-02-04 14:09:12,263:DEBUG:certbot._internal.main:Discovered plugins: PluginsRegistry(PluginEntryPoint#manual,PluginEntryPoint#null,PluginEntryPoint#standalone,PluginEntryPoint#webroot)
2024-02-04 14:09:12,320:DEBUG:certbot._internal.log:Root logging level set at 30
2024-02-04 14:09:12,326:DEBUG:certbot._internal.plugins.selection:Requested authenticator webroot and installer None
2024-02-04 14:09:12,326:DEBUG:certbot._internal.plugins.selection:Single candidate plugin: * webroot
Description: Saves the necessary validation files to a .well-known/acme-challenge/ directory within the nominated webroot path. A seperate HTTP server must be running and serving files from the webroot path. HTTP challenge only (wildcards not supported).
Interfaces: Authenticator, Plugin
Entry point: EntryPoint(name='webroot', value='certbot._internal.plugins.webroot:Authenticator', group='certbot.plugins')
Initialized: <certbot._internal.plugins.webroot.Authenticator object at 0x7f7ead288a30>
Prep: True
2024-02-04 14:09:12,326:DEBUG:certbot._internal.plugins.selection:Selected authenticator <certbot._internal.plugins.webroot.Authenticator object at 0x7f7ead288a30> and installer None
2024-02-04 14:09:12,326:INFO:certbot._internal.plugins.selection:Plugins selected: Authenticator webroot, Installer None
2024-02-04 14:09:12,489:DEBUG:certbot._internal.main:Picked account: <Account(RegistrationResource(body=Registration(key=None, contact=(), agreement=None, status=None, terms_of_service_agreed=None, only_return_existing=None, external_account_binding=None), uri='https://acme-v02.api.letsencrypt.org/acme/acct/1550272667', new_authzr_uri=None, terms_of_service=None), 9b507c65556e201cf96f44fb1f74216d, Meta(creation_dt=datetime.datetime(2024, 2, 2, 17, 5, 57, tzinfo=<UTC>), creation_host='ee38a32c6a85', register_to_eff=None))>
2024-02-04 14:09:12,490:DEBUG:acme.client:Sending GET request to https://acme-v02.api.letsencrypt.org/directory.
2024-02-04 14:09:12,492:DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): acme-v02.api.letsencrypt.org:443
2024-02-04 14:09:12,723:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "GET /directory HTTP/1.1" 200 752
2024-02-04 14:09:12,724:DEBUG:acme.client:Received response:
HTTP 200
Server: nginx
Date: Sun, 04 Feb 2024 14:09:12 GMT
Content-Type: application/json
Content-Length: 752
Connection: keep-alive
Cache-Control: public, max-age=0, no-cache
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800

{
  "LFbyHwEu1BQ": "https://community.letsencrypt.org/t/adding-random-entries-to-the-directory/33417",
  "keyChange": "https://acme-v02.api.letsencrypt.org/acme/key-change",
  "meta": {
    "caaIdentities": [
      "letsencrypt.org"
    ],
    "termsOfService": "https://letsencrypt.org/documents/LE-SA-v1.3-September-21-2022.pdf",
    "website": "https://letsencrypt.org"
  },
  "newAccount": "https://acme-v02.api.letsencrypt.org/acme/new-acct",
  "newNonce": "https://acme-v02.api.letsencrypt.org/acme/new-nonce",
  "newOrder": "https://acme-v02.api.letsencrypt.org/acme/new-order",
  "renewalInfo": "https://acme-v02.api.letsencrypt.org/draft-ietf-acme-ari-02/renewalInfo/",
  "revokeCert": "https://acme-v02.api.letsencrypt.org/acme/revoke-cert"
}
2024-02-04 14:09:12,725:DEBUG:certbot._internal.display.obj:Notifying user: Requesting a certificate for migracion.jadal.pe
2024-02-04 14:09:12,737:DEBUG:acme.client:Requesting fresh nonce
2024-02-04 14:09:12,737:DEBUG:acme.client:Sending HEAD request to https://acme-v02.api.letsencrypt.org/acme/new-nonce.
2024-02-04 14:09:12,811:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "HEAD /acme/new-nonce HTTP/1.1" 200 0
2024-02-04 14:09:12,811:DEBUG:acme.client:Received response:
HTTP 200
Server: nginx
Date: Sun, 04 Feb 2024 14:09:12 GMT
Connection: keep-alive
Cache-Control: public, max-age=0, no-cache
Link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index"
Replay-Nonce: 2ksh1KUsZ8IOWMbygYx1fV8aWCkC7aHUOYX9Xwf84WcgsN-pWq4
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800


2024-02-04 14:09:12,812:DEBUG:acme.client:Storing nonce: 2ksh1KUsZ8IOWMbygYx1fV8aWCkC7aHUOYX9Xwf84WcgsN-pWq4
2024-02-04 14:09:12,812:DEBUG:acme.client:JWS payload:
b'{\n  "identifiers": [\n    {\n      "type": "dns",\n      "value": "migracion.jadal.pe"\n    }\n  ]\n}'
2024-02-04 14:09:12,818:DEBUG:acme.client:Sending POST request to https://acme-v02.api.letsencrypt.org/acme/new-order:
{
  "protected": "eyJhbGciOiAiUlMyNTYiLCAia2lkIjogImh0dHBzOi8vYWNtZS12MDIuYXBpLmxldHNlbmNyeXB0Lm9yZy9hY21lL2FjY3QvMTU1MDI3MjY2NyIsICJub25jZSI6ICIya3NoMUtVc1o4SU9XTWJ5Z1l4MWZWOGFXQ2tDN2FIVU9ZWDlYd2Y4NFdjZ3NOLXBXcTQiLCAidXJsIjogImh0dHBzOi8vYWNtZS12MDIuYXBpLmxldHNlbmNyeXB0Lm9yZy9hY21lL25ldy1vcmRlciJ9",
  "signature": "K56ZYy0UufOYC6dZXvy5wxdpAP2e768VN2J4bZe0dO_3gMDLUL58-Nfgjhxa9q5jhyS6LwKAPxkAh8dNKOYQn5sDV1_QM16HnOp0EbErRrvF7xVjAXH6qrtjEFdis3arsYHgS0rUyZXoLO87nif2PtVa-u5vyi62ARWWwDp34byRjBWu2Ab07ShW2YpNM594c3ncvNJWamDzG8xQCxk_n_O07tbe2IoyiI5GM0LEjW3eAsCnW-718gEaakHxA9CKA8gKGHyIlOsRYUqbqnTDWrujBhX-mRhJlCm-H_X_0Nnt4uqYq-iNWmvBo3w_uTCiajDBzB3zm4x7tFNSae8oPg",
  "payload": "ewogICJpZGVudGlmaWVycyI6IFsKICAgIHsKICAgICAgInR5cGUiOiAiZG5zIiwKICAgICAgInZhbHVlIjogIm1pZ3JhY2lvbi5qYWRhbC5wZSIKICAgIH0KICBdCn0"
}
2024-02-04 14:09:12,917:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "POST /acme/new-order HTTP/1.1" 201 344
2024-02-04 14:09:12,917:DEBUG:acme.client:Received response:
HTTP 201
Server: nginx
Date: Sun, 04 Feb 2024 14:09:12 GMT
Content-Type: application/json
Content-Length: 344
Connection: keep-alive
Boulder-Requester: 1550272667
Cache-Control: public, max-age=0, no-cache
Link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index"
Location: https://acme-v02.api.letsencrypt.org/acme/order/1550272667/241817904937
Replay-Nonce: kRyagOpU0UkJXK9W3KoJj_uxBkmchUGbq3hB0ROBeaHm6XHZocE
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800

{
  "status": "pending",
  "expires": "2024-02-11T14:09:12Z",
  "identifiers": [
    {
      "type": "dns",
      "value": "migracion.jadal.pe"
    }
  ],
  "authorizations": [
    "https://acme-v02.api.letsencrypt.org/acme/authz-v3/311534184077"
  ],
  "finalize": "https://acme-v02.api.letsencrypt.org/acme/finalize/1550272667/241817904937"
}
2024-02-04 14:09:12,917:DEBUG:acme.client:Storing nonce: kRyagOpU0UkJXK9W3KoJj_uxBkmchUGbq3hB0ROBeaHm6XHZocE
2024-02-04 14:09:12,918:DEBUG:acme.client:JWS payload:
b''
2024-02-04 14:09:12,919:DEBUG:acme.client:Sending POST request to https://acme-v02.api.letsencrypt.org/acme/authz-v3/311534184077:
{
  "protected": "eyJhbGciOiAiUlMyNTYiLCAia2lkIjogImh0dHBzOi8vYWNtZS12MDIuYXBpLmxldHNlbmNyeXB0Lm9yZy9hY21lL2FjY3QvMTU1MDI3MjY2NyIsICJub25jZSI6ICJrUnlhZ09wVTBVa0pYSzlXM0tvSmpfdXhCa21jaFVHYnEzaEIwUk9CZWFIbTZYSFpvY0UiLCAidXJsIjogImh0dHBzOi8vYWNtZS12MDIuYXBpLmxldHNlbmNyeXB0Lm9yZy9hY21lL2F1dGh6LXYzLzMxMTUzNDE4NDA3NyJ9",
  "signature": "SOmG6S7AjJej_Bn1hlsRjuDJLZLBjrdJrT9uluEyryVC5L8MtME4oqYROhaNMPXx-4XXe3MNUyvoxnILdNElqzvEpMvCOQcHrTwbrGjjp4e9UfLYmu2EC2MzXNmpIk_uOlm1EOcr7thMNPx5RpkhY4dsHyQ81_zD51jNsxWgIqU0UiiO_DNksFOhY3GUCf0SyUhrDqNXYsVyqxWPFgt4j-gDDv1pKPm6AKBtTDog_l8PBxoGlYl9LzLc-HfNnpZCySqI5DjMCWW8ohge_0ERMrt-1WRdKTW3e66CkrnncmuJqz8MrIbUxVTN-yKmu16ooZ6ZGRSby339FwN4yktEqg",
  "payload": ""
}
2024-02-04 14:09:13,008:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "POST /acme/authz-v3/311534184077 HTTP/1.1" 200 802
2024-02-04 14:09:13,008:DEBUG:acme.client:Received response:
HTTP 200
Server: nginx
Date: Sun, 04 Feb 2024 14:09:12 GMT
Content-Type: application/json
Content-Length: 802
Connection: keep-alive
Boulder-Requester: 1550272667
Cache-Control: public, max-age=0, no-cache
Link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index"
Replay-Nonce: 2ksh1KUskmi87N9bjSE-Xn7U7f1Fhv6XG71sVzlFFJrAWn4QI3Q
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800

{
  "identifier": {
    "type": "dns",
    "value": "migracion.jadal.pe"
  },
  "status": "pending",
  "expires": "2024-02-11T14:09:12Z",
  "challenges": [
    {
      "type": "http-01",
      "status": "pending",
      "url": "https://acme-v02.api.letsencrypt.org/acme/chall-v3/311534184077/D5I54g",
      "token": "KAea270vGD4DoL5cpqxEv6kZIWOExKVdglKMDfx7NKk"
    },
    {
      "type": "dns-01",
      "status": "pending",
      "url": "https://acme-v02.api.letsencrypt.org/acme/chall-v3/311534184077/S1eRiQ",
      "token": "KAea270vGD4DoL5cpqxEv6kZIWOExKVdglKMDfx7NKk"
    },
    {
      "type": "tls-alpn-01",
      "status": "pending",
      "url": "https://acme-v02.api.letsencrypt.org/acme/chall-v3/311534184077/vsMBNQ",
      "token": "KAea270vGD4DoL5cpqxEv6kZIWOExKVdglKMDfx7NKk"
    }
  ]
}
2024-02-04 14:09:13,008:DEBUG:acme.client:Storing nonce: 2ksh1KUskmi87N9bjSE-Xn7U7f1Fhv6XG71sVzlFFJrAWn4QI3Q
2024-02-04 14:09:13,009:INFO:certbot._internal.auth_handler:Performing the following challenges:
2024-02-04 14:09:13,009:INFO:certbot._internal.auth_handler:http-01 challenge for migracion.jadal.pe
2024-02-04 14:09:13,009:INFO:certbot._internal.plugins.webroot:Using the webroot path /usr/share/nginx/html/letsencrypt for all unmatched domains.
2024-02-04 14:09:13,009:DEBUG:certbot._internal.plugins.webroot:Creating root challenges validation dir at /usr/share/nginx/html/letsencrypt/.well-known/acme-challenge
2024-02-04 14:09:13,010:DEBUG:certbot._internal.plugins.webroot:Attempting to save validation to /usr/share/nginx/html/letsencrypt/.well-known/acme-challenge/KAea270vGD4DoL5cpqxEv6kZIWOExKVdglKMDfx7NKk
2024-02-04 14:09:13,011:DEBUG:acme.client:JWS payload:
b'{}'
2024-02-04 14:09:13,012:DEBUG:acme.client:Sending POST request to https://acme-v02.api.letsencrypt.org/acme/chall-v3/311534184077/D5I54g:
{
  "protected": "eyJhbGciOiAiUlMyNTYiLCAia2lkIjogImh0dHBzOi8vYWNtZS12MDIuYXBpLmxldHNlbmNyeXB0Lm9yZy9hY21lL2FjY3QvMTU1MDI3MjY2NyIsICJub25jZSI6ICIya3NoMUtVc2ttaTg3TjlialNFLVhuN1U3ZjFGaHY2WEc3MXNWemxGRkpyQVduNFFJM1EiLCAidXJsIjogImh0dHBzOi8vYWNtZS12MDIuYXBpLmxldHNlbmNyeXB0Lm9yZy9hY21lL2NoYWxsLXYzLzMxMTUzNDE4NDA3Ny9ENUk1NGcifQ",
  "signature": "pvr12rGBYtwqQGKJ_vgN6SdEfmlZVPQuYfhCic2l4CAYsgRMpSsf-4NJOoqlwuoqIxm3SkvIwzfCKLiEctIUv0-ZyJVE8G_JJLYyr7_Qe4m_YSFnsSDFyj14apvZ_rs14NfkPPrhgVQVTj_st1TT7MEDdZtOs5QPg4ggmhbaQQLW7LmvO7-AeF6Sitki-ccnD6UYFACsROsKbeKzqoxfbUMBHRqVJ4sncVd6A6DaJdxX-67hT4wOYVUBg-q7OtOMYchsnIlC3FIaP4c-mL-IyH54gfx1JkHCUTBzDcMzJv4fqZDk1MxCx0NxYOOLBfGisDjPVvaYRCE64OcvfIqfyQ",
  "payload": "e30"
}
2024-02-04 14:09:13,094:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "POST /acme/chall-v3/311534184077/D5I54g HTTP/1.1" 200 187
2024-02-04 14:09:13,095:DEBUG:acme.client:Received response:
HTTP 200
Server: nginx
Date: Sun, 04 Feb 2024 14:09:13 GMT
Content-Type: application/json
Content-Length: 187
Connection: keep-alive
Boulder-Requester: 1550272667
Cache-Control: public, max-age=0, no-cache
Link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index", <https://acme-v02.api.letsencrypt.org/acme/authz-v3/311534184077>;rel="up"
Location: https://acme-v02.api.letsencrypt.org/acme/chall-v3/311534184077/D5I54g
Replay-Nonce: 2ksh1KUsPz4OjT73gWUgP6kE0qwlkgWyewlwARm6enXM0U06y2Y
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800

{
  "type": "http-01",
  "status": "pending",
  "url": "https://acme-v02.api.letsencrypt.org/acme/chall-v3/311534184077/D5I54g",
  "token": "KAea270vGD4DoL5cpqxEv6kZIWOExKVdglKMDfx7NKk"
}
2024-02-04 14:09:13,095:DEBUG:acme.client:Storing nonce: 2ksh1KUsPz4OjT73gWUgP6kE0qwlkgWyewlwARm6enXM0U06y2Y
2024-02-04 14:09:13,096:INFO:certbot._internal.auth_handler:Waiting for verification...
2024-02-04 14:09:14,096:DEBUG:acme.client:JWS payload:
b''
2024-02-04 14:09:14,098:DEBUG:acme.client:Sending POST request to https://acme-v02.api.letsencrypt.org/acme/authz-v3/311534184077:
{
  "protected": "eyJhbGciOiAiUlMyNTYiLCAia2lkIjogImh0dHBzOi8vYWNtZS12MDIuYXBpLmxldHNlbmNyeXB0Lm9yZy9hY21lL2FjY3QvMTU1MDI3MjY2NyIsICJub25jZSI6ICIya3NoMUtVc1B6NE9qVDczZ1dVZ1A2a0UwcXdsa2dXeWV3bHdBUm02ZW5YTTBVMDZ5MlkiLCAidXJsIjogImh0dHBzOi8vYWNtZS12MDIuYXBpLmxldHNlbmNyeXB0Lm9yZy9hY21lL2F1dGh6LXYzLzMxMTUzNDE4NDA3NyJ9",
  "signature": "wauEqEhtj9OUt3iGIqY2CjqTm5Jdh27Qu8yfzSpg1njTlhhnMOe1OuoVLUiyCfES5-xMgHYksUJud5XgtZRMloLmUm65Ubtpzy6KFfRGgKcpyrNzazBxqFDUjBmpFG8rFfhTZg3_7nP8JNgPM_-3zfs-Yr1BkDlI4P-aLFk5NrxWzyAwv8aHfhb-hCCNxNPz0aQwgBB5_iSj4EqMD3b24kbFYCtaXgjHJ6JUYxrPGL7WwaHDgddrPGgBdoEbKeqo7DiwM54PCy5dD9w_6O9aMCO-vTfH7TemnBvvMXxatm5ynexqTyQ7RMbV6XACNa5lCsQkGtPRup6CQis4WN4E7Q",
  "payload": ""
}
2024-02-04 14:09:14,176:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "POST /acme/authz-v3/311534184077 HTTP/1.1" 200 802
2024-02-04 14:09:14,176:DEBUG:acme.client:Received response:
HTTP 200
Server: nginx
Date: Sun, 04 Feb 2024 14:09:14 GMT
Content-Type: application/json
Content-Length: 802
Connection: keep-alive
Boulder-Requester: 1550272667
Cache-Control: public, max-age=0, no-cache
Link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index"
Replay-Nonce: 2ksh1KUsB0TYu8k0CoLwVcLjTgULPiIEqw3c9x5LVNdN8maipgs
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800

{
  "identifier": {
    "type": "dns",
    "value": "migracion.jadal.pe"
  },
  "status": "pending",
  "expires": "2024-02-11T14:09:12Z",
  "challenges": [
    {
      "type": "http-01",
      "status": "pending",
      "url": "https://acme-v02.api.letsencrypt.org/acme/chall-v3/311534184077/D5I54g",
      "token": "KAea270vGD4DoL5cpqxEv6kZIWOExKVdglKMDfx7NKk"
    },
    {
      "type": "dns-01",
      "status": "pending",
      "url": "https://acme-v02.api.letsencrypt.org/acme/chall-v3/311534184077/S1eRiQ",
      "token": "KAea270vGD4DoL5cpqxEv6kZIWOExKVdglKMDfx7NKk"
    },
    {
      "type": "tls-alpn-01",
      "status": "pending",
      "url": "https://acme-v02.api.letsencrypt.org/acme/chall-v3/311534184077/vsMBNQ",
      "token": "KAea270vGD4DoL5cpqxEv6kZIWOExKVdglKMDfx7NKk"
    }
  ]
}
2024-02-04 14:09:14,176:DEBUG:acme.client:Storing nonce: 2ksh1KUsB0TYu8k0CoLwVcLjTgULPiIEqw3c9x5LVNdN8maipgs
2024-02-04 14:09:17,180:DEBUG:acme.client:JWS payload:
b''
2024-02-04 14:09:17,181:DEBUG:acme.client:Sending POST request to https://acme-v02.api.letsencrypt.org/acme/authz-v3/311534184077:
{
  "protected": "eyJhbGciOiAiUlMyNTYiLCAia2lkIjogImh0dHBzOi8vYWNtZS12MDIuYXBpLmxldHNlbmNyeXB0Lm9yZy9hY21lL2FjY3QvMTU1MDI3MjY2NyIsICJub25jZSI6ICIya3NoMUtVc0IwVFl1OGswQ29Md1ZjTGpUZ1VMUGlJRXF3M2M5eDVMVk5kTjhtYWlwZ3MiLCAidXJsIjogImh0dHBzOi8vYWNtZS12MDIuYXBpLmxldHNlbmNyeXB0Lm9yZy9hY21lL2F1dGh6LXYzLzMxMTUzNDE4NDA3NyJ9",
  "signature": "qnvJaqI1l2JQ_fGogYcHHCGVeF3Hr2cEWnVVf_6WqbeUfSigXYwOjBK57maj7sveCq2aQmk-ALT8h3chmMGss38pi6eYxyfjyGRA5dxr5njl7hkttqmlLcSp62buFm4Ffh4N12wPTIcS4VIz87WQh_JSs6Ymi5wK3YbypuCAPrdiPPSJCE4Ecg1mLxuM3yXHc86Kqu_DZLLXljJBY3dM5py2pmWtjtMqMUG6NqAkRHh7Rd7k0tiLb-uLfL3C97YAtwwjuZ9EbspW09vSQLXQH7AUTeBoqFxdlTCPVo-E5ljTwJUnq6NuFWeHVAsfyoWKOaFjzYnvgOIb20c3-WGSUg",
  "payload": ""
}
2024-02-04 14:09:17,260:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "POST /acme/authz-v3/311534184077 HTTP/1.1" 200 1034
2024-02-04 14:09:17,261:DEBUG:acme.client:Received response:
HTTP 200
Server: nginx
Date: Sun, 04 Feb 2024 14:09:17 GMT
Content-Type: application/json
Content-Length: 1034
Connection: keep-alive
Boulder-Requester: 1550272667
Cache-Control: public, max-age=0, no-cache
Link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index"
Replay-Nonce: 2ksh1KUsrCE62mlm8dNSk9o-rfZ3lGcf1XDSMLmztytqcLXQayw
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800

{
  "identifier": {
    "type": "dns",
    "value": "migracion.jadal.pe"
  },
  "status": "invalid",
  "expires": "2024-02-11T14:09:12Z",
  "challenges": [
    {
      "type": "http-01",
      "status": "invalid",
      "error": {
        "type": "urn:ietf:params:acme:error:connection",
        "detail": "3.85.216.85: Fetching http://migracion.jadal.pe/.well-known/acme-challenge/KAea270vGD4DoL5cpqxEv6kZIWOExKVdglKMDfx7NKk: Connection refused",
        "status": 400
      },
      "url": "https://acme-v02.api.letsencrypt.org/acme/chall-v3/311534184077/D5I54g",
      "token": "KAea270vGD4DoL5cpqxEv6kZIWOExKVdglKMDfx7NKk",
      "validationRecord": [
        {
          "url": "http://migracion.jadal.pe/.well-known/acme-challenge/KAea270vGD4DoL5cpqxEv6kZIWOExKVdglKMDfx7NKk",
          "hostname": "migracion.jadal.pe",
          "port": "80",
          "addressesResolved": [
            "3.85.216.85"
          ],
          "addressUsed": "3.85.216.85"
        }
      ],
      "validated": "2024-02-04T14:09:13Z"
    }
  ]
}
2024-02-04 14:09:17,261:DEBUG:acme.client:Storing nonce: 2ksh1KUsrCE62mlm8dNSk9o-rfZ3lGcf1XDSMLmztytqcLXQayw
2024-02-04 14:09:17,261:INFO:certbot._internal.auth_handler:Challenge failed for domain migracion.jadal.pe
2024-02-04 14:09:17,261:INFO:certbot._internal.auth_handler:http-01 challenge for migracion.jadal.pe
2024-02-04 14:09:17,261:DEBUG:certbot._internal.display.obj:Notifying user: 
Certbot failed to authenticate some domains (authenticator: webroot). The Certificate Authority reported these problems:
  Domain: migracion.jadal.pe
  Type:   connection
  Detail: 3.85.216.85: Fetching http://migracion.jadal.pe/.well-known/acme-challenge/KAea270vGD4DoL5cpqxEv6kZIWOExKVdglKMDfx7NKk: Connection refused

Hint: The Certificate Authority failed to download the temporary challenge files created by Certbot. Ensure that the listed domains serve their content from the provided --webroot-path/-w and that files created there can be downloaded from the internet.

2024-02-04 14:09:17,262:DEBUG:certbot._internal.error_handler:Encountered exception:
Traceback (most recent call last):
  File "/opt/certbot/src/certbot/certbot/_internal/auth_handler.py", line 108, in handle_authorizations
    self._poll_authorizations(authzrs, max_retries, max_time_mins, best_effort)
  File "/opt/certbot/src/certbot/certbot/_internal/auth_handler.py", line 212, in _poll_authorizations
    raise errors.AuthorizationError('Some challenges have failed.')
certbot.errors.AuthorizationError: Some challenges have failed.

2024-02-04 14:09:17,262:DEBUG:certbot._internal.error_handler:Calling registered functions
2024-02-04 14:09:17,262:INFO:certbot._internal.auth_handler:Cleaning up challenges
2024-02-04 14:09:17,262:DEBUG:certbot._internal.plugins.webroot:Removing /usr/share/nginx/html/letsencrypt/.well-known/acme-challenge/KAea270vGD4DoL5cpqxEv6kZIWOExKVdglKMDfx7NKk
2024-02-04 14:09:17,263:DEBUG:certbot._internal.plugins.webroot:All challenges cleaned up
2024-02-04 14:09:17,263:DEBUG:certbot._internal.log:Exiting abnormally:
Traceback (most recent call last):
  File "/usr/local/bin/certbot", line 33, in <module>
    sys.exit(load_entry_point('certbot', 'console_scripts', 'certbot')())
  File "/opt/certbot/src/certbot/certbot/main.py", line 19, in main
    return internal_main.main(cli_args)
  File "/opt/certbot/src/certbot/certbot/_internal/main.py", line 1869, in main
    return config.func(config, plugins)
  File "/opt/certbot/src/certbot/certbot/_internal/main.py", line 1600, in certonly
    lineage = _get_and_save_cert(le_client, config, domains, certname, lineage)
  File "/opt/certbot/src/certbot/certbot/_internal/main.py", line 143, in _get_and_save_cert
    lineage = le_client.obtain_and_enroll_certificate(domains, certname)
  File "/opt/certbot/src/certbot/certbot/_internal/client.py", line 517, in obtain_and_enroll_certificate
    cert, chain, key, _ = self.obtain_certificate(domains)
  File "/opt/certbot/src/certbot/certbot/_internal/client.py", line 428, in obtain_certificate
    orderr = self._get_order_and_authorizations(csr.data, self.config.allow_subset_of_names)
  File "/opt/certbot/src/certbot/certbot/_internal/client.py", line 496, in _get_order_and_authorizations
    authzr = self.auth_handler.handle_authorizations(orderr, self.config, best_effort)
  File "/opt/certbot/src/certbot/certbot/_internal/auth_handler.py", line 108, in handle_authorizations
    self._poll_authorizations(authzrs, max_retries, max_time_mins, best_effort)
  File "/opt/certbot/src/certbot/certbot/_internal/auth_handler.py", line 212, in _poll_authorizations
    raise errors.AuthorizationError('Some challenges have failed.')
certbot.errors.AuthorizationError: Some challenges have failed.
2024-02-04 14:09:17,264:ERROR:certbot._internal.log:Some challenges have failed.
