2024-02-02 17:25:02,122:DEBUG:certbot._internal.main:certbot version: 2.8.0
2024-02-02 17:25:02,123:DEBUG:certbot._internal.main:Location of certbot entry point: /usr/local/bin/certbot
2024-02-02 17:25:02,123:DEBUG:certbot._internal.main:Arguments: ['--webroot', '--webroot-path=/usr/share/nginx/html/letsencrypt', '--email', 'desarrollo.jadalsoftware@gmail.com', '--agree-tos', '--no-eff-email', '-d', 'migracion.jadal.pe']
2024-02-02 17:25:02,123:DEBUG:certbot._internal.main:Discovered plugins: PluginsRegistry(PluginEntryPoint#manual,PluginEntryPoint#null,PluginEntryPoint#standalone,PluginEntryPoint#webroot)
2024-02-02 17:25:02,137:DEBUG:certbot._internal.log:Root logging level set at 30
2024-02-02 17:25:02,138:DEBUG:certbot._internal.plugins.selection:Requested authenticator webroot and installer None
2024-02-02 17:25:02,138:DEBUG:certbot._internal.plugins.selection:Single candidate plugin: * webroot
Description: Saves the necessary validation files to a .well-known/acme-challenge/ directory within the nominated webroot path. A seperate HTTP server must be running and serving files from the webroot path. HTTP challenge only (wildcards not supported).
Interfaces: Authenticator, Plugin
Entry point: EntryPoint(name='webroot', value='certbot._internal.plugins.webroot:Authenticator', group='certbot.plugins')
Initialized: <certbot._internal.plugins.webroot.Authenticator object at 0x7f799f394a30>
Prep: True
2024-02-02 17:25:02,138:DEBUG:certbot._internal.plugins.selection:Selected authenticator <certbot._internal.plugins.webroot.Authenticator object at 0x7f799f394a30> and installer None
2024-02-02 17:25:02,139:INFO:certbot._internal.plugins.selection:Plugins selected: Authenticator webroot, Installer None
2024-02-02 17:25:02,198:DEBUG:certbot._internal.main:Picked account: <Account(RegistrationResource(body=Registration(key=None, contact=(), agreement=None, status=None, terms_of_service_agreed=None, only_return_existing=None, external_account_binding=None), uri='https://acme-v02.api.letsencrypt.org/acme/acct/1550272667', new_authzr_uri=None, terms_of_service=None), 9b507c65556e201cf96f44fb1f74216d, Meta(creation_dt=datetime.datetime(2024, 2, 2, 17, 5, 57, tzinfo=<UTC>), creation_host='ee38a32c6a85', register_to_eff=None))>
2024-02-02 17:25:02,199:DEBUG:acme.client:Sending GET request to https://acme-v02.api.letsencrypt.org/directory.
2024-02-02 17:25:02,201:DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): acme-v02.api.letsencrypt.org:443
2024-02-02 17:25:02,377:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "GET /directory HTTP/1.1" 200 752
2024-02-02 17:25:02,377:DEBUG:acme.client:Received response:
HTTP 200
Server: nginx
Date: Fri, 02 Feb 2024 17:25:02 GMT
Content-Type: application/json
Content-Length: 752
Connection: keep-alive
Cache-Control: public, max-age=0, no-cache
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800

{
  "hCP1qXe7Kj0": "https://community.letsencrypt.org/t/adding-random-entries-to-the-directory/33417",
  "keyChange": "https://acme-v02.api.letsencrypt.org/acme/key-change",
  "meta": {
    "caaIdentities": [
      "letsencrypt.org"
    ],
    "termsOfService": "https://letsencrypt.org/documents/LE-SA-v1.3-September-21-2022.pdf",
    "website": "https://letsencrypt.org"
  },
  "newAccount": "https://acme-v02.api.letsencrypt.org/acme/new-acct",
  "newNonce": "https://acme-v02.api.letsencrypt.org/acme/new-nonce",
  "newOrder": "https://acme-v02.api.letsencrypt.org/acme/new-order",
  "renewalInfo": "https://acme-v02.api.letsencrypt.org/draft-ietf-acme-ari-02/renewalInfo/",
  "revokeCert": "https://acme-v02.api.letsencrypt.org/acme/revoke-cert"
}
2024-02-02 17:25:02,378:DEBUG:certbot._internal.display.obj:Notifying user: Requesting a certificate for migracion.jadal.pe
2024-02-02 17:25:02,382:DEBUG:acme.client:Requesting fresh nonce
2024-02-02 17:25:02,382:DEBUG:acme.client:Sending HEAD request to https://acme-v02.api.letsencrypt.org/acme/new-nonce.
2024-02-02 17:25:02,439:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "HEAD /acme/new-nonce HTTP/1.1" 200 0
2024-02-02 17:25:02,440:DEBUG:acme.client:Received response:
HTTP 200
Server: nginx
Date: Fri, 02 Feb 2024 17:25:02 GMT
Connection: keep-alive
Cache-Control: public, max-age=0, no-cache
Link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index"
Replay-Nonce: kRyagOpUHQB-as4zQA_CV0RI70craePZS9g13QVI6IoIlhYhYc0
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800


2024-02-02 17:25:02,440:DEBUG:acme.client:Storing nonce: kRyagOpUHQB-as4zQA_CV0RI70craePZS9g13QVI6IoIlhYhYc0
2024-02-02 17:25:02,440:DEBUG:acme.client:JWS payload:
b'{\n  "identifiers": [\n    {\n      "type": "dns",\n      "value": "migracion.jadal.pe"\n    }\n  ]\n}'
2024-02-02 17:25:02,443:DEBUG:acme.client:Sending POST request to https://acme-v02.api.letsencrypt.org/acme/new-order:
{
  "protected": "eyJhbGciOiAiUlMyNTYiLCAia2lkIjogImh0dHBzOi8vYWNtZS12MDIuYXBpLmxldHNlbmNyeXB0Lm9yZy9hY21lL2FjY3QvMTU1MDI3MjY2NyIsICJub25jZSI6ICJrUnlhZ09wVUhRQi1hczR6UUFfQ1YwUkk3MGNyYWVQWlM5ZzEzUVZJNklvSWxoWWhZYzAiLCAidXJsIjogImh0dHBzOi8vYWNtZS12MDIuYXBpLmxldHNlbmNyeXB0Lm9yZy9hY21lL25ldy1vcmRlciJ9",
  "signature": "YHnAKNs0cvIl_F3xoQ6pwP7_rp8tz1Rrst2KTiVnOyq5t-94z9YFPn9uUYWj8kSB7DVGGoXhnA35DK-6v-eH3lalDwTu5M6Qwib8VsxVkpGAIgQRzWdHoViilQGTdLPYGUpDo2GM8JxqvC2uHBl3at6vP_u2amK1BEuIffnsybcv0pwudXgrFuZs5uS_9QemyRpFHvgg0hyTZYJPtQQp0lgahNX_XdBRCnFr1ZIC1g93OIhUlFh3JhLGrvG6HwO152xIWg_4LAF42TYqKMVZZyYDaxTApo6rklmQWtRnxdud_NgvdZG5YX7pdRyZ0fpP2rQayQXLat8ROCXAO2fi4g",
  "payload": "ewogICJpZGVudGlmaWVycyI6IFsKICAgIHsKICAgICAgInR5cGUiOiAiZG5zIiwKICAgICAgInZhbHVlIjogIm1pZ3JhY2lvbi5qYWRhbC5wZSIKICAgIH0KICBdCn0"
}
2024-02-02 17:25:02,524:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "POST /acme/new-order HTTP/1.1" 201 344
2024-02-02 17:25:02,524:DEBUG:acme.client:Received response:
HTTP 201
Server: nginx
Date: Fri, 02 Feb 2024 17:25:02 GMT
Content-Type: application/json
Content-Length: 344
Connection: keep-alive
Boulder-Requester: 1550272667
Cache-Control: public, max-age=0, no-cache
Link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index"
Location: https://acme-v02.api.letsencrypt.org/acme/order/1550272667/241331917237
Replay-Nonce: 2ksh1KUszbgytW-zue3JeUzl4nvdvIz4-8m4b2xXdqz0Ms9t8fc
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800

{
  "status": "pending",
  "expires": "2024-02-09T17:25:02Z",
  "identifiers": [
    {
      "type": "dns",
      "value": "migracion.jadal.pe"
    }
  ],
  "authorizations": [
    "https://acme-v02.api.letsencrypt.org/acme/authz-v3/310852991947"
  ],
  "finalize": "https://acme-v02.api.letsencrypt.org/acme/finalize/1550272667/241331917237"
}
2024-02-02 17:25:02,524:DEBUG:acme.client:Storing nonce: 2ksh1KUszbgytW-zue3JeUzl4nvdvIz4-8m4b2xXdqz0Ms9t8fc
2024-02-02 17:25:02,525:DEBUG:acme.client:JWS payload:
b''
2024-02-02 17:25:02,526:DEBUG:acme.client:Sending POST request to https://acme-v02.api.letsencrypt.org/acme/authz-v3/310852991947:
{
  "protected": "eyJhbGciOiAiUlMyNTYiLCAia2lkIjogImh0dHBzOi8vYWNtZS12MDIuYXBpLmxldHNlbmNyeXB0Lm9yZy9hY21lL2FjY3QvMTU1MDI3MjY2NyIsICJub25jZSI6ICIya3NoMUtVc3piZ3l0Vy16dWUzSmVVemw0bnZkdkl6NC04bTRiMnhYZHF6ME1zOXQ4ZmMiLCAidXJsIjogImh0dHBzOi8vYWNtZS12MDIuYXBpLmxldHNlbmNyeXB0Lm9yZy9hY21lL2F1dGh6LXYzLzMxMDg1Mjk5MTk0NyJ9",
  "signature": "izluppDaiompIcRQYZHJ5UhSig6ZYQdIrZDok9JQgR6WcDkm5yu2OuR-om_ng3kDlDLZdTZIFjxl9ngJXUW_DTL4QCVYv8vT3VICSyJ0wAXoCEaCGui0KhsrUfBEFsxseDlsZK-Nwh3-I1EJeR8-rvA_YbV0iKXdh6GKj9WAPtGflpGru2Mv8J0A9TpmjZ19uDqCaeWo9nRKtfcMGQ_Ky82Qs1RIUQZ48tOzBd2OGOQsratU4ZiPADFI45b4DQy9iBFFKeZcdlWegC7Cf1Imrry2nK2hE_cK0tYAoaR9q567BL1ehZZHEuqvF6nb99G1Gm5tprl5PCF6UW3v-JdIwQ",
  "payload": ""
}
2024-02-02 17:25:02,591:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "POST /acme/authz-v3/310852991947 HTTP/1.1" 200 802
2024-02-02 17:25:02,591:DEBUG:acme.client:Received response:
HTTP 200
Server: nginx
Date: Fri, 02 Feb 2024 17:25:02 GMT
Content-Type: application/json
Content-Length: 802
Connection: keep-alive
Boulder-Requester: 1550272667
Cache-Control: public, max-age=0, no-cache
Link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index"
Replay-Nonce: kRyagOpUYIScdaCN2ys1Mkqec2AP5l0jOFCKlMy7bTnJzALNphA
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800

{
  "identifier": {
    "type": "dns",
    "value": "migracion.jadal.pe"
  },
  "status": "pending",
  "expires": "2024-02-09T17:25:02Z",
  "challenges": [
    {
      "type": "http-01",
      "status": "pending",
      "url": "https://acme-v02.api.letsencrypt.org/acme/chall-v3/310852991947/wTcUzw",
      "token": "BKgYlt0t2aadPBLQoOD-f2FUcA7Y0PZjeWNl8OTkqLA"
    },
    {
      "type": "dns-01",
      "status": "pending",
      "url": "https://acme-v02.api.letsencrypt.org/acme/chall-v3/310852991947/vPuhNA",
      "token": "BKgYlt0t2aadPBLQoOD-f2FUcA7Y0PZjeWNl8OTkqLA"
    },
    {
      "type": "tls-alpn-01",
      "status": "pending",
      "url": "https://acme-v02.api.letsencrypt.org/acme/chall-v3/310852991947/Cwy8Xg",
      "token": "BKgYlt0t2aadPBLQoOD-f2FUcA7Y0PZjeWNl8OTkqLA"
    }
  ]
}
2024-02-02 17:25:02,591:DEBUG:acme.client:Storing nonce: kRyagOpUYIScdaCN2ys1Mkqec2AP5l0jOFCKlMy7bTnJzALNphA
2024-02-02 17:25:02,592:INFO:certbot._internal.auth_handler:Performing the following challenges:
2024-02-02 17:25:02,592:INFO:certbot._internal.auth_handler:http-01 challenge for migracion.jadal.pe
2024-02-02 17:25:02,592:INFO:certbot._internal.plugins.webroot:Using the webroot path /usr/share/nginx/html/letsencrypt for all unmatched domains.
2024-02-02 17:25:02,592:DEBUG:certbot._internal.plugins.webroot:Creating root challenges validation dir at /usr/share/nginx/html/letsencrypt/.well-known/acme-challenge
2024-02-02 17:25:02,593:DEBUG:certbot._internal.plugins.webroot:Attempting to save validation to /usr/share/nginx/html/letsencrypt/.well-known/acme-challenge/BKgYlt0t2aadPBLQoOD-f2FUcA7Y0PZjeWNl8OTkqLA
2024-02-02 17:25:02,594:DEBUG:acme.client:JWS payload:
b'{}'
2024-02-02 17:25:02,595:DEBUG:acme.client:Sending POST request to https://acme-v02.api.letsencrypt.org/acme/chall-v3/310852991947/wTcUzw:
{
  "protected": "eyJhbGciOiAiUlMyNTYiLCAia2lkIjogImh0dHBzOi8vYWNtZS12MDIuYXBpLmxldHNlbmNyeXB0Lm9yZy9hY21lL2FjY3QvMTU1MDI3MjY2NyIsICJub25jZSI6ICJrUnlhZ09wVVlJU2NkYUNOMnlzMU1rcWVjMkFQNWwwak9GQ0tsTXk3YlRuSnpBTE5waEEiLCAidXJsIjogImh0dHBzOi8vYWNtZS12MDIuYXBpLmxldHNlbmNyeXB0Lm9yZy9hY21lL2NoYWxsLXYzLzMxMDg1Mjk5MTk0Ny93VGNVencifQ",
  "signature": "mc5SBcmZaU_ea52fNu7CXahw7oNh_DXRHJDi6pUDD5gMXrRE-r6YwHWPPX4Mzsk8EnT_-ZVvIvziddVDb2rsC4Fkt7JcVgWwUz3_TCVaAMI54LiJW55aKhpP93J9gcqa3qOa2qUVThPUUYBDPbyZIzMlgBg4NNVf7mAQtJPdKqk7MxBNuvrUdNr6yyn3aCNVbnKLJGln8iGXgnlNf7xzCP6UzqysrGWmFaiMl_a6Zmxt1jI5uDR7EH9eu7LzkITk72HyaswSCYjihymA-1NX_8WarkxzGcBN1EJ3wX0YKj4peK1EF0DfEbcGsBJNfxoU7u0I5oxTTvN38YeypExkDw",
  "payload": "e30"
}
2024-02-02 17:25:02,662:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "POST /acme/chall-v3/310852991947/wTcUzw HTTP/1.1" 200 187
2024-02-02 17:25:02,663:DEBUG:acme.client:Received response:
HTTP 200
Server: nginx
Date: Fri, 02 Feb 2024 17:25:02 GMT
Content-Type: application/json
Content-Length: 187
Connection: keep-alive
Boulder-Requester: 1550272667
Cache-Control: public, max-age=0, no-cache
Link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index", <https://acme-v02.api.letsencrypt.org/acme/authz-v3/310852991947>;rel="up"
Location: https://acme-v02.api.letsencrypt.org/acme/chall-v3/310852991947/wTcUzw
Replay-Nonce: 2ksh1KUsIfvGj8Q9hyEnx50otrPXLa8Ecp16UZYQtgiSFx2Zdtc
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800

{
  "type": "http-01",
  "status": "pending",
  "url": "https://acme-v02.api.letsencrypt.org/acme/chall-v3/310852991947/wTcUzw",
  "token": "BKgYlt0t2aadPBLQoOD-f2FUcA7Y0PZjeWNl8OTkqLA"
}
2024-02-02 17:25:02,663:DEBUG:acme.client:Storing nonce: 2ksh1KUsIfvGj8Q9hyEnx50otrPXLa8Ecp16UZYQtgiSFx2Zdtc
2024-02-02 17:25:02,663:INFO:certbot._internal.auth_handler:Waiting for verification...
2024-02-02 17:25:03,664:DEBUG:acme.client:JWS payload:
b''
2024-02-02 17:25:03,666:DEBUG:acme.client:Sending POST request to https://acme-v02.api.letsencrypt.org/acme/authz-v3/310852991947:
{
  "protected": "eyJhbGciOiAiUlMyNTYiLCAia2lkIjogImh0dHBzOi8vYWNtZS12MDIuYXBpLmxldHNlbmNyeXB0Lm9yZy9hY21lL2FjY3QvMTU1MDI3MjY2NyIsICJub25jZSI6ICIya3NoMUtVc0lmdkdqOFE5aHlFbng1MG90clBYTGE4RWNwMTZVWllRdGdpU0Z4MlpkdGMiLCAidXJsIjogImh0dHBzOi8vYWNtZS12MDIuYXBpLmxldHNlbmNyeXB0Lm9yZy9hY21lL2F1dGh6LXYzLzMxMDg1Mjk5MTk0NyJ9",
  "signature": "BI9Jo4om4xgMBHgl1AdD5YjnreLJ5YqVgtAKtBRmQYuoIW8-_MLpKE-99C4efn_C0CzFxERlmwqPeJXk-px3tGB4nnSSrx1KDxkyTmmAgKgPG6rl0Uw8A8VdkGW4fGD10M1luzA-07kNluKInDZ6eztb4uS1-Oq012ogzTFLwXBS99g52YWi4qQIMWYLGnr02lEV8xTtweTKoNxlFl5GIAT9GeM718GUgpQovQtpX8JjK8-rXhlB1Y9xaIAQBH6FOsYebS3Rkk3ji3VgSNImQQRNnCAcZfKzxwDfvhCW5-oDX8jCQZKtF_H-ivfSGzas_2wwCylwG69wEFGthMv_6g",
  "payload": ""
}
2024-02-02 17:25:03,732:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "POST /acme/authz-v3/310852991947 HTTP/1.1" 200 1034
2024-02-02 17:25:03,732:DEBUG:acme.client:Received response:
HTTP 200
Server: nginx
Date: Fri, 02 Feb 2024 17:25:03 GMT
Content-Type: application/json
Content-Length: 1034
Connection: keep-alive
Boulder-Requester: 1550272667
Cache-Control: public, max-age=0, no-cache
Link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index"
Replay-Nonce: 2ksh1KUse_FW_oD4c_XXPX_3G2TEY5t8TcCyLCYVKzJhczswqi4
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800

{
  "identifier": {
    "type": "dns",
    "value": "migracion.jadal.pe"
  },
  "status": "invalid",
  "expires": "2024-02-09T17:25:02Z",
  "challenges": [
    {
      "type": "http-01",
      "status": "invalid",
      "error": {
        "type": "urn:ietf:params:acme:error:connection",
        "detail": "3.85.216.85: Fetching http://migracion.jadal.pe/.well-known/acme-challenge/BKgYlt0t2aadPBLQoOD-f2FUcA7Y0PZjeWNl8OTkqLA: Connection refused",
        "status": 400
      },
      "url": "https://acme-v02.api.letsencrypt.org/acme/chall-v3/310852991947/wTcUzw",
      "token": "BKgYlt0t2aadPBLQoOD-f2FUcA7Y0PZjeWNl8OTkqLA",
      "validationRecord": [
        {
          "url": "http://migracion.jadal.pe/.well-known/acme-challenge/BKgYlt0t2aadPBLQoOD-f2FUcA7Y0PZjeWNl8OTkqLA",
          "hostname": "migracion.jadal.pe",
          "port": "80",
          "addressesResolved": [
            "3.85.216.85"
          ],
          "addressUsed": "3.85.216.85"
        }
      ],
      "validated": "2024-02-02T17:25:02Z"
    }
  ]
}
2024-02-02 17:25:03,733:DEBUG:acme.client:Storing nonce: 2ksh1KUse_FW_oD4c_XXPX_3G2TEY5t8TcCyLCYVKzJhczswqi4
2024-02-02 17:25:03,733:INFO:certbot._internal.auth_handler:Challenge failed for domain migracion.jadal.pe
2024-02-02 17:25:03,733:INFO:certbot._internal.auth_handler:http-01 challenge for migracion.jadal.pe
2024-02-02 17:25:03,733:DEBUG:certbot._internal.display.obj:Notifying user: 
Certbot failed to authenticate some domains (authenticator: webroot). The Certificate Authority reported these problems:
  Domain: migracion.jadal.pe
  Type:   connection
  Detail: 3.85.216.85: Fetching http://migracion.jadal.pe/.well-known/acme-challenge/BKgYlt0t2aadPBLQoOD-f2FUcA7Y0PZjeWNl8OTkqLA: Connection refused

Hint: The Certificate Authority failed to download the temporary challenge files created by Certbot. Ensure that the listed domains serve their content from the provided --webroot-path/-w and that files created there can be downloaded from the internet.

2024-02-02 17:25:03,734:DEBUG:certbot._internal.error_handler:Encountered exception:
Traceback (most recent call last):
  File "/opt/certbot/src/certbot/certbot/_internal/auth_handler.py", line 108, in handle_authorizations
    self._poll_authorizations(authzrs, max_retries, max_time_mins, best_effort)
  File "/opt/certbot/src/certbot/certbot/_internal/auth_handler.py", line 212, in _poll_authorizations
    raise errors.AuthorizationError('Some challenges have failed.')
certbot.errors.AuthorizationError: Some challenges have failed.

2024-02-02 17:25:03,734:DEBUG:certbot._internal.error_handler:Calling registered functions
2024-02-02 17:25:03,734:INFO:certbot._internal.auth_handler:Cleaning up challenges
2024-02-02 17:25:03,734:DEBUG:certbot._internal.plugins.webroot:Removing /usr/share/nginx/html/letsencrypt/.well-known/acme-challenge/BKgYlt0t2aadPBLQoOD-f2FUcA7Y0PZjeWNl8OTkqLA
2024-02-02 17:25:03,735:DEBUG:certbot._internal.plugins.webroot:All challenges cleaned up
2024-02-02 17:25:03,735:DEBUG:certbot._internal.log:Exiting abnormally:
Traceback (most recent call last):
  File "/usr/local/bin/certbot", line 33, in <module>
    sys.exit(load_entry_point('certbot', 'console_scripts', 'certbot')())
  File "/opt/certbot/src/certbot/certbot/main.py", line 19, in main
    return internal_main.main(cli_args)
  File "/opt/certbot/src/certbot/certbot/_internal/main.py", line 1869, in main
    return config.func(config, plugins)
  File "/opt/certbot/src/certbot/certbot/_internal/main.py", line 1600, in certonly
    lineage = _get_and_save_cert(le_client, config, domains, certname, lineage)
  File "/opt/certbot/src/certbot/certbot/_internal/main.py", line 143, in _get_and_save_cert
    lineage = le_client.obtain_and_enroll_certificate(domains, certname)
  File "/opt/certbot/src/certbot/certbot/_internal/client.py", line 517, in obtain_and_enroll_certificate
    cert, chain, key, _ = self.obtain_certificate(domains)
  File "/opt/certbot/src/certbot/certbot/_internal/client.py", line 428, in obtain_certificate
    orderr = self._get_order_and_authorizations(csr.data, self.config.allow_subset_of_names)
  File "/opt/certbot/src/certbot/certbot/_internal/client.py", line 496, in _get_order_and_authorizations
    authzr = self.auth_handler.handle_authorizations(orderr, self.config, best_effort)
  File "/opt/certbot/src/certbot/certbot/_internal/auth_handler.py", line 108, in handle_authorizations
    self._poll_authorizations(authzrs, max_retries, max_time_mins, best_effort)
  File "/opt/certbot/src/certbot/certbot/_internal/auth_handler.py", line 212, in _poll_authorizations
    raise errors.AuthorizationError('Some challenges have failed.')
certbot.errors.AuthorizationError: Some challenges have failed.
2024-02-02 17:25:03,736:ERROR:certbot._internal.log:Some challenges have failed.
